-- Data Intelligence Agent PostgreSQL seed data.
-- Scenario: ecommerce operating analytics with explainable June anomalies.

SET client_encoding = 'UTF8';
SET timezone = 'Asia/Shanghai';

DROP TABLE IF EXISTS knowledge_chunks CASCADE;
DROP TABLE IF EXISTS fact_refunds CASCADE;
DROP TABLE IF EXISTS fact_marketing_spend CASCADE;
DROP TABLE IF EXISTS fact_daily_traffic CASCADE;
DROP TABLE IF EXISTS fact_orders CASCADE;
DROP TABLE IF EXISTS dim_customer CASCADE;
DROP TABLE IF EXISTS dim_channel CASCADE;
DROP TABLE IF EXISTS dim_product CASCADE;
DROP TABLE IF EXISTS dim_region CASCADE;
DROP TABLE IF EXISTS dim_date CASCADE;

CREATE TABLE dim_date (
    date_id DATE PRIMARY KEY,
    year INT NOT NULL,
    month INT NOT NULL,
    day INT NOT NULL,
    month_label VARCHAR(7) NOT NULL,
    is_weekend BOOLEAN NOT NULL
);
COMMENT ON TABLE dim_date IS '日期维度表';
COMMENT ON COLUMN dim_date.month_label IS '月份标签，格式 YYYY-MM';

CREATE TABLE dim_region (
    region_id INT PRIMARY KEY,
    region_name VARCHAR(50) NOT NULL,
    province VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    city_tier VARCHAR(20) NOT NULL
);
COMMENT ON TABLE dim_region IS '区域维度表，支持大区、省份、城市下钻';

CREATE TABLE dim_product (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    unit_cost NUMERIC(12,2) NOT NULL,
    list_price NUMERIC(12,2) NOT NULL
);
COMMENT ON TABLE dim_product IS '商品维度表，包含品类、品牌、成本和标价';

CREATE TABLE dim_channel (
    channel_id INT PRIMARY KEY,
    channel_name VARCHAR(50) NOT NULL,
    channel_type VARCHAR(50) NOT NULL
);
COMMENT ON TABLE dim_channel IS '渠道维度表，包含官网、抖音、京东、天猫、线下等渠道';

CREATE TABLE dim_customer (
    customer_id INT PRIMARY KEY,
    customer_type VARCHAR(30) NOT NULL,
    member_level VARCHAR(30) NOT NULL,
    region_id INT NOT NULL REFERENCES dim_region(region_id),
    registered_at DATE NOT NULL
);
COMMENT ON TABLE dim_customer IS '客户维度表，支持客户类型、会员等级和区域分析';

CREATE TABLE fact_orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL REFERENCES dim_date(date_id),
    customer_id INT NOT NULL REFERENCES dim_customer(customer_id),
    product_id INT NOT NULL REFERENCES dim_product(product_id),
    region_id INT NOT NULL REFERENCES dim_region(region_id),
    channel_id INT NOT NULL REFERENCES dim_channel(channel_id),
    quantity INT NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    order_amount NUMERIC(12,2) NOT NULL,
    product_cost NUMERIC(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'paid'
);
COMMENT ON TABLE fact_orders IS '订单事实表。GMV 使用 order_amount 汇总，有效订单 status=paid';

CREATE TABLE fact_refunds (
    refund_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_date DATE NOT NULL REFERENCES dim_date(date_id),
    order_id BIGINT NOT NULL REFERENCES fact_orders(order_id),
    refund_amount NUMERIC(12,2) NOT NULL,
    refund_reason VARCHAR(100) NOT NULL
);
COMMENT ON TABLE fact_refunds IS '退款事实表，用于净销售额、退款率和利润分析';

CREATE TABLE fact_marketing_spend (
    spend_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spend_date DATE NOT NULL REFERENCES dim_date(date_id),
    channel_id INT NOT NULL REFERENCES dim_channel(channel_id),
    region_id INT NOT NULL REFERENCES dim_region(region_id),
    spend_amount NUMERIC(12,2) NOT NULL
);
COMMENT ON TABLE fact_marketing_spend IS '营销投放事实表，用于渠道 ROI 分析';

CREATE TABLE fact_daily_traffic (
    traffic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    traffic_date DATE NOT NULL REFERENCES dim_date(date_id),
    channel_id INT NOT NULL REFERENCES dim_channel(channel_id),
    region_id INT NOT NULL REFERENCES dim_region(region_id),
    visits INT NOT NULL,
    product_views INT NOT NULL,
    add_to_cart INT NOT NULL,
    paid_orders INT NOT NULL
);
COMMENT ON TABLE fact_daily_traffic IS '每日流量和转化漏斗事实表';

CREATE TABLE knowledge_chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    keywords TEXT NOT NULL,
    embedding_json TEXT
);
COMMENT ON TABLE knowledge_chunks IS 'RAG 知识片段表。当前使用关键词检索降级，embedding_json 预留给向量检索';

INSERT INTO dim_date (date_id, year, month, day, month_label, is_weekend)
SELECT d::date, EXTRACT(YEAR FROM d)::int, EXTRACT(MONTH FROM d)::int,
       EXTRACT(DAY FROM d)::int, TO_CHAR(d, 'YYYY-MM'),
       EXTRACT(ISODOW FROM d)::int IN (6, 7)
FROM generate_series('2026-01-01'::date, '2026-06-30'::date, interval '1 day') d;

INSERT INTO dim_region VALUES
(1, '华北', '北京', '北京', '一线'),
(2, '华北', '天津', '天津', '新一线'),
(3, '华北', '河北', '石家庄', '二线'),
(4, '华东', '上海', '上海', '一线'),
(5, '华东', '浙江', '杭州', '新一线'),
(6, '华南', '广东', '广州', '一线'),
(7, '西南', '四川', '成都', '新一线'),
(8, '华中', '湖北', '武汉', '新一线');

INSERT INTO dim_product VALUES
(1, '旗舰智能手表 Pro', '智能硬件', 'Aster', 860, 1599),
(2, '运动蓝牙耳机', '智能硬件', 'Aster', 180, 399),
(3, '轻薄办公笔记本', '电脑办公', 'North', 3900, 5999),
(4, '人体工学椅', '电脑办公', 'North', 520, 999),
(5, '高端咖啡豆礼盒', '生活方式', 'Mellow', 88, 199),
(6, '空气净化器', '家用电器', 'CleanAir', 760, 1299),
(7, '扫地机器人', '家用电器', 'CleanAir', 1100, 2199),
(8, '会员服务年卡', '数字服务', 'Aster', 80, 399),
(9, '智能投影仪', '家用电器', 'North', 1450, 2899),
(10, '高保湿护肤套装', '美妆个护', 'Mellow', 160, 499);

INSERT INTO dim_channel VALUES
(1, '官网', '自营'),
(2, '抖音', '内容电商'),
(3, '京东', '货架电商'),
(4, '天猫', '货架电商'),
(5, '线下门店', '线下');

INSERT INTO dim_customer (customer_id, customer_type, member_level, region_id, registered_at)
SELECT
    1000 + n,
    CASE WHEN n % 5 = 0 THEN '企业客户' WHEN n % 3 = 0 THEN '高价值用户' ELSE '普通用户' END,
    CASE WHEN n % 7 = 0 THEN '黑金' WHEN n % 4 = 0 THEN '黄金' WHEN n % 2 = 0 THEN '白银' ELSE '普通' END,
    ((n - 1) % 8) + 1,
    ('2025-01-01'::date + (n % 360))
FROM generate_series(1, 240) n;

INSERT INTO fact_orders (
    order_date, customer_id, product_id, region_id, channel_id,
    quantity, unit_price, discount_amount, order_amount, product_cost, status
)
SELECT
    d.date_id,
    1000 + (((EXTRACT(DOY FROM d.date_id)::int * 13 + r.region_id * 17 + p.product_id * 19 + c.channel_id * 23) % 240) + 1),
    p.product_id,
    r.region_id,
    c.channel_id,
    q.quantity,
    ROUND((p.list_price * factor.price_factor)::numeric, 2),
    ROUND((p.list_price * factor.discount_factor * q.quantity)::numeric, 2),
    ROUND(((p.list_price * factor.price_factor * q.quantity) - (p.list_price * factor.discount_factor * q.quantity))::numeric, 2),
    ROUND((p.unit_cost * factor.cost_factor * q.quantity)::numeric, 2),
    'paid'
FROM dim_date d
CROSS JOIN dim_region r
CROSS JOIN dim_channel c
JOIN dim_product p ON p.product_id = ((EXTRACT(DOY FROM d.date_id)::int + r.region_id + c.channel_id) % 10) + 1
CROSS JOIN LATERAL (
    SELECT CASE
        WHEN d.month = 6 AND r.province = '北京' THEN 0
        WHEN d.month = 6 AND c.channel_name = '抖音' AND r.region_name = '华北' THEN 1
        WHEN d.is_weekend THEN 2
        ELSE 1
    END + ((EXTRACT(DOY FROM d.date_id)::int + r.region_id + c.channel_id) % 3) AS quantity
) q
CROSS JOIN LATERAL (
    SELECT
        CASE WHEN d.month = 6 AND p.category = '家用电器' THEN 1.02 ELSE 1.00 END AS price_factor,
        CASE WHEN d.month = 6 AND c.channel_name = '京东' THEN 0.11 ELSE 0.06 END AS discount_factor,
        CASE WHEN d.month = 6 AND p.category IN ('家用电器', '电脑办公') THEN 1.12 ELSE 1.00 END AS cost_factor
) factor
WHERE q.quantity > 0;

INSERT INTO fact_refunds (refund_date, order_id, refund_amount, refund_reason)
SELECT
    LEAST(o.order_date + ((o.order_id % 5)::int + 1), '2026-06-30'::date),
    o.order_id,
    ROUND((o.order_amount * CASE
        WHEN d.month = 6 AND p.category = '家用电器' THEN 0.72
        ELSE 0.45
    END)::numeric, 2),
    CASE
        WHEN d.month = 6 AND p.category = '家用电器' THEN '质量/安装问题'
        WHEN o.order_id % 3 = 0 THEN '七天无理由'
        ELSE '物流破损'
    END
FROM fact_orders o
JOIN dim_date d ON d.date_id = o.order_date
JOIN dim_product p ON p.product_id = o.product_id
JOIN dim_channel c ON c.channel_id = o.channel_id
WHERE
    (d.month = 6 AND p.category = '家用电器' AND o.order_id % 3 = 0)
    OR (d.month < 6 AND o.order_id % 17 = 0)
    OR (d.month = 6 AND c.channel_name = '京东' AND o.order_id % 11 = 0);

INSERT INTO fact_marketing_spend (spend_date, channel_id, region_id, spend_amount)
SELECT
    d.date_id,
    c.channel_id,
    r.region_id,
    ROUND((CASE
        WHEN d.month = 6 AND c.channel_name = '抖音' THEN 5200
        WHEN c.channel_name = '抖音' THEN 3200
        WHEN c.channel_name IN ('京东', '天猫') THEN 2600
        WHEN c.channel_name = '官网' THEN 1200
        ELSE 800
    END * CASE WHEN r.region_name = '华北' THEN 1.25 ELSE 1.0 END)::numeric, 2)
FROM dim_date d
CROSS JOIN dim_channel c
CROSS JOIN dim_region r;

INSERT INTO fact_daily_traffic (traffic_date, channel_id, region_id, visits, product_views, add_to_cart, paid_orders)
SELECT
    d.date_id,
    c.channel_id,
    r.region_id,
    base.visits,
    (base.visits * 0.62)::int,
    (base.visits * factor.cart_rate)::int,
    (base.visits * factor.conversion_rate)::int
FROM dim_date d
CROSS JOIN dim_channel c
CROSS JOIN dim_region r
CROSS JOIN LATERAL (
    SELECT (
        CASE WHEN c.channel_name = '抖音' THEN 5200
             WHEN c.channel_name IN ('京东', '天猫') THEN 3600
             WHEN c.channel_name = '官网' THEN 2300
             ELSE 1400 END
        * CASE WHEN r.region_name = '华北' THEN 1.25 ELSE 1.0 END
        * CASE WHEN d.is_weekend THEN 1.12 ELSE 1.0 END
    )::int AS visits
) base
CROSS JOIN LATERAL (
    SELECT
        CASE WHEN d.month = 6 AND c.channel_name = '抖音' AND r.region_name = '华北' THEN 0.045 ELSE 0.078 END AS conversion_rate,
        CASE WHEN d.month = 6 AND c.channel_name = '抖音' AND r.region_name = '华北' THEN 0.12 ELSE 0.18 END AS cart_rate
) factor;

INSERT INTO knowledge_chunks (source, content, keywords) VALUES
('metrics.md', 'GMV = 有效订单 order_amount 汇总。有效订单指 fact_orders.status = paid。', 'GMV 销售额 有效订单 order_amount'),
('metrics.md', '净销售额 = GMV - 退款金额。退款金额来自 fact_refunds.refund_amount。', '净销售额 退款 refund_amount'),
('metrics.md', '毛利额 = GMV - product_cost - refund_amount，毛利率 = 毛利额 / GMV。', '毛利 毛利率 product_cost 利润'),
('metrics.md', '渠道 ROI = 净销售额 / 营销花费。营销花费来自 fact_marketing_spend.spend_amount。', 'ROI 渠道 营销花费 spend'),
('business_rules.md', '华北区域包括北京、天津、河北。北京市场属于华北区域。', '华北 北京 天津 河北 区域'),
('business_rules.md', '高价值用户定义为 dim_customer.customer_type = 高价值用户。', '高价值用户 customer_type'),
('analysis_playbooks.md', '销售下降分析先看整体趋势，再按地区、品类、渠道拆解，最后计算下降贡献度。', '销售下降 归因 地区 品类 渠道 贡献度'),
('analysis_playbooks.md', '利润下降分析需要同时检查 GMV、退款金额、商品成本和营销花费。', '利润下降 GMV 退款 成本 营销');

CREATE INDEX idx_fact_orders_date ON fact_orders(order_date);
CREATE INDEX idx_fact_orders_region ON fact_orders(region_id);
CREATE INDEX idx_fact_orders_channel ON fact_orders(channel_id);
CREATE INDEX idx_fact_orders_product ON fact_orders(product_id);
CREATE INDEX idx_fact_refunds_order ON fact_refunds(order_id);
